name: TrollYourPlayers
main: me.technogeek48.TrollYourPlayers.TrollYourPlayers
version: 0.2
commands:
   silentsmite:
      description: This command is WIP.
      usage: /<command> [player]
      permission: TrollYourPlayers.silentsmite
      permission-message: Command not found.
   trollmode:
      description: This command is WIP.
      usage: /<command> [player]
      permission: TrollYourPlayers.trollmode
      permission-message: Command not found.