name: TrollYourPlayers
main: me.technogeek48.TrollYourPlayers.TrollYourPlayers
version: 1.0
commands:
   silentsmite:
      description: Smites specified player.
      usage: /<command> [player]
      permission: TrollYourPlayers.silentsmite
      permission-message: Command not found.
   trollmode:
      description: Enables trollmode.
      usage: /<command>
      permission: TrollYourPlayers.trollmode
      permission-message: Command not found.
   trollmus:
      description: Plays strange sounds to the designated player.
      usage: /<command> [player]
      permission: TrollYourPlayers.trollmus
      permission-message: Command not found.
   supersmite:
      description: Smites and explodes player.
      usage: /<command> [player]
      permission: TrollYourPlayers.supersmite
      permission-message: Command not found.
   trollbed:
      description: Explodes specified players bedspawn.
      usage: /<command> [player]
      permission: TrollYourPlayers.trollbed
      permission-message: Command not found.
   fallofdoom:
      description: Teleports players to the sky.
      usage: /<command> [player]
      permission: TrollYourPlayers.fallofdoom
      permission-message: Command not found.
   ragequit:
      description: Makes the player look like he ragequit.
      usage: /<command> [player]
      permission: TrollYourPlayers.fallofdoom
      permission-message: Command not found.
   trolltp:
      description: Teleports players to destination.
      usage: /<command> [player]
      permission: TrollYourPlayers.trolltp
      permission-message: Command not found.
   trollanvil:
      description: Places 4 anvils above the players head.
      usage: /<command> [player]
      permission-message: Command not found.
      permission: TrollYourPlayers.trollanvil
   anvilpointer:
      description: Places 4 anvils above targeted block.
      usage: /<command> [player]
      permission: TrollYourPlayers.anvilpointer
      permission-message: Command not found.
   digstraightdown:
      description: Nuffsaid.
      usage: /<command> [player]
      permission: TrollYourPlayers.digstraightdown
      permission-message: Command not found.
   void:
      description: teleports specified player Keeps X and Z. Sets Y to -14 (In the void)
      usage: /<command> [player]
      permission: TrollYourPlayers.void
   tripout:
      description: Gives nausea to specified player. 
      permission: TrollYourPlayers.tripout
      permission-message: Command not found.
   mobraid:
      usage: /<command> [player]
      permission: TrollYourPlayers.mobraid
      description: spawns several mobs where you are looking
      permission-message: Command not found.
   epicsmite:
      description: Epiclysmite the specified player. 
      usage: /<command> [player]
      permission: TrollYourPlayers.mobraid
      permission-message: Command not found.
   epicsmitepointer:
      description: Epiclysmites the block ur looking at
      usage: /<command> [player]
      permission: TrollYourPlayers.mobraid
      permission-message: Command not found.
   testcommand:
      description: testcommand
      usage: /<command> [player]
      permission: TrollYourPlayers.mobraid
      permission-message: Command not found.
   trollarrow:
      description: acts as arrowmachinegun!
      usage: /<command> [player]
      permission: TrollYourPlayers.mobraid
      permission-message: Command not found.
   trollswap:
      description: acts as arrowmachinegun!
      usage: /<command> [player]
      permission: TrollYourPlayers.mobraid
      permission-message: Command not found.
   trolldragon:
      description: acts as arrowmachinegun!
      usage: /<command> [player]
      permission: TrollYourPlayers.mobraid
      permission-message: Command not found.
   trollweb:
      description: acts as arrowmachinegun!
      usage: /<command> [player]
      permission: TrollYourPlayers.mobraid
      permission-message: Command not found.
   fakeop:
      description: acts as arrowmachinegun!
      usage: /<command> [player]
      permission: TrollYourPlayers.mobraid
      permission-message: Command not found.
